[package]
name = "sc-node"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "NAPI bindings for signalis-core"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
rand = { workspace = true }

# Internal crates
sc-curve25519 = { workspace = true }
sc-ed25519 = { workspace = true }
sc-xed25519 = { workspace = true }
sc-hkdf = { workspace = true }
sc-pbkdf2 = { workspace = true }
sc-aes = { workspace = true }
sc-hmac = { workspace = true }
sc-sha256 = { workspace = true }
sc-chacha20poly1305 = { workspace = true }
sc-utils = { workspace = true }
sc-encoding = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
