[package]
name = "sc-node"
description = "NAPI-RS Node.js bindings for Signalis Core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }

sc-curve25519 = { workspace = true }
sc-hkdf = { workspace = true }
sc-aes = { workspace = true }
sc-hmac = { workspace = true }
sc-sha256 = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
